#!/usr/bin/env node
/**
 * scripts/brevo-to-jsx.mjs
 *
 * Converts a Brevo email template export file into React Email .jsx components.
 * Skips any template with "newsletter" in the name (case-insensitive).
 *
 * Usage:
 *   node scripts/brevo-to-jsx.mjs "<path-to-brevo_templates.html>"
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { JSDOM } from 'jsdom';
import { randomUUID } from 'crypto';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, '..');
const EMAILS_DIR = path.join(PROJECT_ROOT, 'emails');

// Standard DOM node type constants
const TEXT_NODE = 3;
const ELEMENT_NODE = 1;

// ─── Entry ────────────────────────────────────────────────────────────────────

const inputPath = process.argv[2];
if (!inputPath) {
  console.error('Usage: node scripts/brevo-to-jsx.mjs <path-to-brevo_templates.html>');
  process.exit(1);
}

const html = fs.readFileSync(inputPath, 'utf-8');
const templates = parseBrevoTemplates(html);
const nonNewsletter = templates.filter(t => !t.name.toLowerCase().includes('newsletter'));

console.log(`Found ${templates.length} templates total, ${nonNewsletter.length} non-newsletter.\n`);

if (!fs.existsSync(EMAILS_DIR)) {
  fs.mkdirSync(EMAILS_DIR, { recursive: true });
}

const generated = [];
const maildraftTemplates = [];

const DEFAULT_THEME = {
  maxWidth: 600,
  backgroundColor: '#ffffff',
  fontName: 'Open Sans',
  fontFamily: 'Open Sans, sans-serif',
  bodyFontSize: 16,
  linkColor: '#333333',
};

for (const template of nonNewsletter) {
  const slug = toSlug(template.name);
  const componentName = toPascalCase(slug);
  try {
    const doc = parseBrevoHtml(template.rawHtml);

    // MailDraft template object (TipTap JSON + metadata)
    const now = new Date().toISOString();
    maildraftTemplates.push({
      id: randomUUID(),
      name: `#${template.brevoId} — ${template.name}`,
      subject: template.subject || '',
      doc,
      theme: { ...DEFAULT_THEME },
      variables: template.variables.length > 0
        ? template.variables
        : [{ name: 'first_name', fallback: 'there' }],
      createdAt: now,
      updatedAt: now,
    });

    // React Email .jsx file
    const jsx = tiptapToJsx(doc, componentName, template.variables, template.subject);
    const outPath = path.join(EMAILS_DIR, `${slug}.jsx`);
    fs.writeFileSync(outPath, jsx, 'utf-8');
    generated.push({ slug, componentName, name: template.name });
    console.log(`  ✓ #${template.brevoId} ${slug}.jsx`);
  } catch (err) {
    console.error(`  ✗ #${template.brevoId} ${slug}: ${err.message}`);
    if (process.env.DEBUG) console.error(err.stack);
  }
}

// Barrel export
const indexContent = [
  '// Auto-generated by scripts/brevo-to-jsx.mjs',
  '',
  ...generated.map(({ slug, componentName }) =>
    `export { default as ${componentName} } from './${slug}.jsx';`
  ),
  '',
].join('\n');

fs.writeFileSync(path.join(EMAILS_DIR, 'index.js'), indexContent, 'utf-8');

// MailDraft seed JSON (inject into localStorage to populate the templates tab)
const seedPath = path.join(PROJECT_ROOT, 'scripts', 'maildraft-seed.json');
fs.writeFileSync(seedPath, JSON.stringify(maildraftTemplates, null, 2), 'utf-8');

console.log(`\nDone. Generated ${generated.length} .jsx files in ${EMAILS_DIR}`);
console.log(`Seed JSON → ${seedPath}`);


// ═══════════════════════════════════════════════════════════════════════════════
// SECTION 1: parseBrevoTemplates — extract template metadata from the export file
// ═══════════════════════════════════════════════════════════════════════════════

function parseBrevoTemplates(htmlString) {
  const { document } = new JSDOM(htmlString).window;
  const results = [];

  const sections = document.querySelectorAll('.template-section[id^="template-"]');
  for (const section of sections) {
    const brevoId = section.id.replace('template-', '').trim();

    const h2 = section.querySelector('.template-header h2');
    let name = 'Template';
    if (h2) {
      const h2Clone = h2.cloneNode(true);
      h2Clone.querySelectorAll('.badge').forEach(el => el.remove());
      name = h2Clone.textContent.trim().replace(/^#\d+\s*[–—-]\s*/, '').trim();
    }

    // Subject line from <span>Subject: <em>...</em></span>
    let subject = '';
    const metaSpans = section.querySelectorAll('.template-meta span');
    for (const span of metaSpans) {
      if (span.textContent.startsWith('Subject:')) {
        const em = span.querySelector('em');
        if (em) subject = em.textContent.trim();
      }
    }

    const variables = [];
    const varCodes = section.querySelectorAll('.variables-box code');
    for (const code of varCodes) {
      const text = code.textContent.trim();
      const match = text.match(/^\{\{\s*(.+?)\s*\}\}\s*[→\->]+\s*(.*)$/);
      if (match) variables.push({ name: match[1].trim(), fallback: match[2].trim() });
    }

    const pre = section.querySelector('details.raw-html-toggle pre');
    if (!pre) continue;
    const rawHtml = pre.textContent.trim();
    if (!rawHtml) continue;

    results.push({ brevoId, name, subject, variables, rawHtml });
  }

  return results;
}


// ═══════════════════════════════════════════════════════════════════════════════
// SECTION 2: parseBrevoHtml — convert raw Brevo HTML → TipTap JSON
//   Ported from src/lib/parseBrevoHtml.js; DOMParser replaced with jsdom.
// ═══════════════════════════════════════════════════════════════════════════════

function parseBrevoHtml(htmlString) {
  const cleaned = stripJinja(htmlString);
  const { document } = new JSDOM(cleaned, { contentType: 'text/html' }).window;

  const nlBody = document.querySelector('table.nl2go-body-table');
  let blocks;
  if (nlBody) {
    blocks = parseNl2GoTemplate(nlBody);
  } else {
    blocks = parseSimpleBrevoTemplate(document.body);
  }

  if (!blocks || blocks.length === 0) blocks = [emptyParagraph()];
  return { type: 'doc', content: blocks };
}

function stripJinja(html) {
  return html
    .replace(/\{%-?\s*(if|elif|else|endif|for|endfor|block|endblock|extends|set|raw|endraw)[^%]*?%\}/gi, '')
    .replace(/<!--\[if[^\]]*\]>[\s\S]*?<!\[endif\]-->/gi, '')
    .replace(/<!--\[if[^\]]*\]>[\s\S]*?<!\[endif\]>/gi, '');
}

function parseNl2GoTemplate(nlBodyTable) {
  const blocks = [];
  const wrapperTable = nlBodyTable.querySelector('table[width="600"], table.r0-o');
  const rootCell = wrapperTable
    ? wrapperTable.querySelector('tr > td')
    : nlBodyTable.querySelector('tr > td');

  if (!rootCell) return extractFlatContent(nlBodyTable);

  for (const sectionTable of directChildTables(rootCell)) {
    blocks.push(...parseSectionTable(sectionTable));
  }
  return blocks;
}

function directChildTables(el) {
  const tables = [];
  for (const child of el.children) {
    if (child.tagName === 'TABLE') tables.push(child);
  }
  return tables;
}

function parseSectionTable(table) {
  const spacer = detectSpacer(table);
  if (spacer) return [spacer];

  const isFooter = isFooterSection(table);
  const columns = getColumnCells(table);

  if (columns.length === 0) return extractFlatContent(table);

  if (columns.length === 1) {
    return parseCellContent(columns[0]);
  }

  if (columns.length === 2) {
    const ratio = isFooter ? '50-50' : detectRatio(columns[0], columns[1]);
    const leftBlocks = parseCellContent(columns[0]);
    const rightBlocks = parseCellContent(columns[1]);
    if (leftBlocks.length > 0 || rightBlocks.length > 0) {
      return [makeColumns(leftBlocks, rightBlocks, ratio)];
    }
    return [];
  }

  // 3+ columns: flatten
  const blocks = [];
  for (const col of columns) blocks.push(...parseCellContent(col));
  return blocks;
}

function getColumnCells(table) {
  const rows = table.querySelectorAll('tr');
  for (const row of rows) {
    const ths = Array.from(row.children).filter(c => c.tagName === 'TH');
    if (ths.length > 0) return ths;
  }
  for (const row of rows) {
    const tds = Array.from(row.children).filter(c => {
      if (c.tagName !== 'TD') return false;
      const w = c.getAttribute('width') || '';
      return w.includes('%') && parseFloat(w) < 100;
    });
    if (tds.length > 1) return tds;
  }
  return [];
}

function getDirectCells(table) {
  const cells = [];
  const bodies = Array.from(table.children).filter(
    el => el.tagName === 'TBODY' || el.tagName === 'THEAD',
  );
  const containers = bodies.length > 0 ? bodies : [table];
  for (const container of containers) {
    for (const row of container.children) {
      if (row.tagName !== 'TR') continue;
      for (const cell of row.children) {
        if (cell.tagName === 'TD' || cell.tagName === 'TH') cells.push(cell);
      }
    }
  }
  return cells;
}

function detectRatio(left, right) {
  const lw = parseFloat(left.getAttribute('width') || left.style?.width || '50');
  const rw = parseFloat(right.getAttribute('width') || right.style?.width || '50');
  if (!lw || !rw) return '50-50';
  const leftPct = Math.round((lw / (lw + rw)) * 100);
  if (leftPct <= 34) return '33-66';
  if (leftPct >= 66) return '66-33';
  return '50-50';
}

function isFooterSection(table) {
  for (const el of table.querySelectorAll('[style]')) {
    const style = el.getAttribute('style') || '';
    if (style.includes('#eff2f7') || style.includes('eff2f7')) return true;
    if (el.style && el.style.backgroundColor === 'rgb(239, 242, 247)') return true;
  }
  return false;
}

function detectSpacer(table) {
  const cells = getDirectCells(table).filter(cell => {
    const row = cell.parentElement;
    return !row?.classList.contains('nl2go-responsive-hide');
  });
  if (cells.length === 0) return null;
  for (const td of cells) {
    const height = parseInt(td.getAttribute('height') || '0', 10);
    const hasContent = td.textContent.replace(/\u00AD/g, '').trim().length > 0;
    const hasImgs = td.querySelectorAll('img').length > 0;
    if (height > 0 && !hasContent && !hasImgs) {
      return { type: 'blockSpacer', attrs: { height } };
    }
  }
  return null;
}

function parseCellContent(cell) {
  const blocks = [];
  walkCellForBlocks(cell, blocks);
  return blocks;
}

function walkCellForBlocks(el, blocks) {
  if (isImageOnlyCell(el)) {
    const imgBlock = makeImageBlock(el);
    if (imgBlock) { blocks.push(imgBlock); return; }
  }

  for (const child of el.children) {
    const tag = child.tagName;
    if (tag === 'TABLE') {
      blocks.push(...extractBlocksFromTable(child));
    } else if (tag === 'DIV') {
      blocks.push(...extractTextFromDiv(child));
    } else if (tag === 'P') {
      const para = parseInlineContent(child);
      if (para) blocks.push(para);
    } else if (/^H[1-4]$/.test(tag)) {
      const h = makeHeadingBlock(child);
      if (h) blocks.push(h);
    } else if (tag === 'UL' || tag === 'OL') {
      const list = makeListBlock(child);
      if (list) blocks.push(list);
    } else if (tag === 'TD' || tag === 'TH' || tag === 'TBODY' || tag === 'TR') {
      walkCellForBlocks(child, blocks);
    }
  }
}

function extractBlocksFromTable(table) {
  const spacer = detectSpacer(table);
  if (spacer) return [spacer];

  const divider = detectDivider(table);
  if (divider) return [divider];

  const social = detectSocialIcons(table);
  if (social) return [social];

  const btn = detectButton(table);
  if (btn) return [btn];

  const imgBlock = detectImageTable(table);
  if (imgBlock) return [imgBlock];

  const columns = getColumnCells(table);
  if (columns.length === 2) {
    const left = parseCellContent(columns[0]);
    const right = parseCellContent(columns[1]);
    if (left.length > 0 || right.length > 0) {
      return [makeColumns(left, right, detectRatio(columns[0], columns[1]))];
    }
  }
  if (columns.length > 2) {
    const blocks = [];
    for (const col of columns) blocks.push(...parseCellContent(col));
    return blocks;
  }

  const blocks = [];
  for (const cell of getDirectCells(table)) walkCellForBlocks(cell, blocks);
  return blocks;
}

function detectDivider(table) {
  const style = table.getAttribute('style') || '';
  if (style.includes('border-top')) {
    const color = extractStyleProp(style, 'border-top-color') ||
                  extractStyleProp(style, 'border-color') || '#E5E7EB';
    const thickness = parseInt(extractStyleProp(style, 'border-top-width') || '1', 10);
    return { type: 'blockDivider', attrs: { color, thickness, width: 100 } };
  }
  const hr = table.querySelector('hr');
  if (hr) {
    const hrStyle = hr.getAttribute('style') || '';
    const color = extractStyleProp(hrStyle, 'border-color') || hr.getAttribute('color') || '#E5E7EB';
    return { type: 'blockDivider', attrs: { color, thickness: 1, width: 100 } };
  }
  return null;
}

function detectSocialIcons(table) {
  const NETWORKS = ['instagram', 'facebook', 'twitter', 'linkedin', 'youtube', 'tiktok', 'pinterest', 'snapchat'];
  const icons = [];
  for (const a of table.querySelectorAll('a[href]')) {
    const href = a.getAttribute('href') || '';
    const img = a.querySelector('img');
    if (!img) continue;
    const src = img.getAttribute('src') || '';
    let network = '';
    for (const net of NETWORKS) {
      if (src.toLowerCase().includes(net) || href.toLowerCase().includes(net)) {
        network = net; break;
      }
    }
    if (!network) continue;
    const w = parseInt(img.getAttribute('width') || '0', 10);
    if (w > 0 && w <= 64) icons.push({ network, href, iconUrl: src });
  }
  return icons.length > 0 ? { type: 'blockSocialIcons', attrs: { icons } } : null;
}

function detectButton(table) {
  for (const td of table.querySelectorAll('td')) {
    const style = td.getAttribute('style') || '';
    const bgColor = extractStyleProp(style, 'background') ||
                    extractStyleProp(style, 'background-color') ||
                    td.getAttribute('bgcolor');
    if (!bgColor) continue;
    const a = td.querySelector('a');
    if (!a) continue;
    const label = a.textContent.trim();
    if (!label) continue;
    const href = a.getAttribute('href') || '#';
    const borderRadius = parseInt(
      extractStyleProp(style, 'border-radius') ||
      extractStyleProp(style, '-webkit-border-radius') || '6', 10);
    const fontSize = parseInt(extractStyleProp(style, 'font-size') || '14', 10);
    const normalizedBg = normalizeCssColor(bgColor);
    if (!normalizedBg || normalizedBg === '#ffffff' || normalizedBg === '#fff') continue;
    return {
      type: 'blockButton',
      attrs: {
        label, href,
        backgroundColor: normalizedBg,
        color: '#ffffff',
        borderRadius: isNaN(borderRadius) ? 6 : borderRadius,
        paddingTop: 12, paddingBottom: 12, paddingLeft: 24, paddingRight: 24,
        fontSize: isNaN(fontSize) ? 14 : fontSize,
        fontWeight: 600, align: 'center',
      },
    };
  }
  return null;
}

function detectImageTable(table) {
  const allImgs = table.querySelectorAll('img');
  if (allImgs.length === 0) return null;
  const tableText = table.textContent.replace(/\u00AD|\s/g, '').trim();
  if (tableText.length > 8) return null;

  for (const td of table.querySelectorAll('td')) {
    const style = td.getAttribute('style') || '';
    if (!style.includes('font-size: 0') && !style.includes('font-size:0') &&
        !style.includes('line-height: 0') && !style.includes('line-height:0')) continue;
    const img = td.querySelector('img');
    if (!img) continue;
    return makeImageBlockFromImg(img, td);
  }
  if (allImgs.length === 1) return makeImageBlockFromImg(allImgs[0], null);
  return null;
}

function isImageOnlyCell(el) {
  return el.querySelectorAll('img').length > 0 &&
         el.textContent.replace(/\u00AD/g, '').trim() === '';
}

function makeImageBlock(cell) {
  const img = cell.querySelector('img');
  return img ? makeImageBlockFromImg(img, cell) : null;
}

function makeImageBlockFromImg(img, containerEl) {
  const src   = img.getAttribute('src') || '';
  const alt   = img.getAttribute('alt') || '';
  const width = img.getAttribute('width') || '100%';

  let align = 'center';
  if (containerEl) {
    const s = containerEl.getAttribute('style') || '';
    const a = containerEl.getAttribute('align') || '';
    if (a === 'left'  || s.includes('text-align: left'))  align = 'left';
    if (a === 'right' || s.includes('text-align: right')) align = 'right';
  }

  let href = null;
  const parentA = img.closest('a[href]');
  if (parentA) href = parentA.getAttribute('href');

  const wNum = parseInt(width, 10);
  if (wNum > 0 && wNum < 10) return null;
  if (src.includes('track') && wNum <= 1) return null;

  let finalWidth = '100%';
  if (!isNaN(wNum)) finalWidth = wNum >= 540 ? '100%' : `${wNum}px`;
  else if (typeof width === 'string' && width.includes('%')) finalWidth = width;

  return { type: 'blockImage', attrs: { src, alt, width: finalWidth, align, href } };
}

function makeHeadingBlock(el) {
  const level = Math.min(parseInt(el.tagName[1], 10) || 2, 3);
  const content = parseInlineNodes(el);
  if (!content || content.length === 0) return null;
  return { type: 'heading', attrs: { level }, content };
}

function makeListBlock(listEl) {
  const items = [];
  for (const li of listEl.querySelectorAll(':scope > li')) {
    const content = parseInlineNodes(li);
    if (content && content.length > 0) {
      items.push({ type: 'listItem', content: [{ type: 'paragraph', content }] });
    }
  }
  if (items.length === 0) return null;
  return { type: listEl.tagName === 'OL' ? 'orderedList' : 'bulletList', content: items };
}

function makeColumns(leftBlocks, rightBlocks, ratio) {
  return {
    type: 'blockColumns',
    attrs: { ratio },
    content: [
      { type: 'blockColumn', content: leftBlocks.length > 0 ? leftBlocks : [emptyParagraph()] },
      { type: 'blockColumn', content: rightBlocks.length > 0 ? rightBlocks : [emptyParagraph()] },
    ],
  };
}

function extractTextFromDiv(div) {
  const blocks = [];
  if (isImageOnlyCell(div)) {
    const img = div.querySelector('img');
    if (img) {
      const b = makeImageBlockFromImg(img, div);
      if (b) blocks.push(b);
    }
    return blocks;
  }

  const blockChildren = Array.from(div.children).filter(el =>
    ['P', 'H1', 'H2', 'H3', 'H4', 'UL', 'OL', 'DIV', 'BLOCKQUOTE'].includes(el.tagName)
  );

  if (blockChildren.length > 0) {
    for (const child of blockChildren) {
      if (/^H[1-4]$/.test(child.tagName)) {
        const h = makeHeadingBlock(child);
        if (h) blocks.push(h);
      } else if (child.tagName === 'UL' || child.tagName === 'OL') {
        const list = makeListBlock(child);
        if (list) blocks.push(list);
      } else if (child.tagName === 'DIV') {
        blocks.push(...extractTextFromDiv(child));
      } else if (child.tagName === 'P') {
        const para = parseInlineContent(child);
        if (para) blocks.push(para);
      }
    }
  } else {
    const para = parseInlineContent(div);
    if (para) blocks.push(para);
  }
  return blocks;
}

function parseInlineContent(el) {
  const style = el.getAttribute('style') || '';
  let textAlign = extractStyleProp(style, 'text-align') || 'left';
  if (!['left', 'center', 'right', 'justify'].includes(textAlign)) textAlign = 'left';
  const content = parseInlineNodes(el);
  const hasRealContent = content.some(n => n.type === 'text' ? (n.text || '').trim().length > 0 : true);
  if (!hasRealContent) return null;
  return { type: 'paragraph', attrs: { textAlign }, content };
}

function parseInlineNodes(el) {
  const nodes = [];
  for (const child of el.childNodes) {
    if (child.nodeType === TEXT_NODE) {
      const text = child.textContent;
      if (text) nodes.push({ type: 'text', text });
    } else if (child.nodeType === ELEMENT_NODE) {
      const tag = child.tagName;
      if (tag === 'BR') {
        nodes.push({ type: 'hardBreak' });
      } else if (tag === 'STRONG' || tag === 'B') {
        const inner = parseInlineNodes(child);
        addMark(inner, 'bold');
        nodes.push(...inner);
      } else if (tag === 'EM' || tag === 'I') {
        const inner = parseInlineNodes(child);
        addMark(inner, 'italic');
        nodes.push(...inner);
      } else if (tag === 'U') {
        const inner = parseInlineNodes(child);
        addMark(inner, 'underline');
        nodes.push(...inner);
      } else if (tag === 'A') {
        const href = child.getAttribute('href') || '#';
        const inner = parseInlineNodes(child);
        addMark(inner, 'link', { href });
        nodes.push(...inner);
      } else if (tag === 'SPAN') {
        const inner = parseInlineNodes(child);
        const spanStyle = child.getAttribute('style') || '';
        const color = extractStyleProp(spanStyle, 'color');
        if (color) addMark(inner, 'textStyle', { color: normalizeCssColor(color) || color });
        nodes.push(...inner);
      } else if (tag !== 'IMG') {
        nodes.push(...parseInlineNodes(child));
      }
    }
  }
  return mergeTextNodes(nodes);
}

function addMark(nodes, type, attrs) {
  for (const node of nodes) {
    if (node.type !== 'text') continue;
    node.marks = node.marks || [];
    if (!node.marks.find(m => m.type === type)) {
      node.marks.push(attrs ? { type, attrs } : { type });
    }
  }
}

function mergeTextNodes(nodes) {
  const result = [];
  for (const node of nodes) {
    if (node.type !== 'text') { result.push(node); continue; }
    if (!node.text) continue;
    const last = result[result.length - 1];
    const sameMarks = JSON.stringify(last?.marks || []) === JSON.stringify(node.marks || []);
    if (last && last.type === 'text' && sameMarks) {
      last.text += node.text;
    } else {
      result.push({ ...node });
    }
  }
  return result;
}

function parseSimpleBrevoTemplate(body) {
  const blocks = [];
  const contentTable = body.querySelector('table[width="570"], table[width="600"]') || body.querySelector('table');
  if (!contentTable) return extractFlatContent(body);

  const tbody = contentTable.querySelector(':scope > tbody') || contentTable;
  const rows = Array.from(tbody.children).filter(el => el.tagName === 'TR');

  for (const row of rows) {
    const td = row.querySelector('td');
    if (!td) continue;
    const height = parseInt(td.getAttribute('height') || '0', 10);
    const tdStyle = td.getAttribute('style') || '';
    const text = td.textContent.replace(/\u00AD/g, '').trim();

    if (height > 0 && !text) {
      blocks.push({ type: 'blockSpacer', attrs: { height } });
      continue;
    }

    const img = td.querySelector('img');
    if (img && text === (img.getAttribute('alt') || '').trim()) {
      const b = makeImageBlockFromImg(img, td);
      if (b) { blocks.push(b); continue; }
    }

    const nestedTable = td.querySelector('table');
    if (nestedTable) {
      const btn = detectButton(nestedTable);
      if (btn) { blocks.push(btn); continue; }
    }

    if (text) {
      const fontSize = parseInt(extractStyleProp(tdStyle, 'font-size') || '0', 10);
      const align = extractStyleProp(tdStyle, 'text-align') || td.getAttribute('align') || 'left';
      const color = normalizeCssColor(extractStyleProp(tdStyle, 'color') || '#000000');
      if (fontSize >= 18) {
        blocks.push({
          type: 'heading',
          attrs: { level: fontSize >= 24 ? 1 : 2 },
          content: [{ type: 'text', text }],
        });
      } else {
        blocks.push({
          type: 'paragraph',
          attrs: { textAlign: align },
          content: [{
            type: 'text', text,
            ...(color && color !== '#000000' ? { marks: [{ type: 'textStyle', attrs: { color } }] } : {}),
          }],
        });
      }
    }
  }
  return blocks;
}

function extractFlatContent(el) {
  const blocks = [];
  for (const img of el.querySelectorAll('img')) {
    const b = makeImageBlockFromImg(img, null);
    if (b) blocks.push(b);
  }
  const text = el.textContent.replace(/\u00AD/g, '').trim();
  if (text && el.querySelectorAll('img').length === 0) {
    blocks.push({ type: 'paragraph', content: [{ type: 'text', text }] });
  }
  return blocks;
}

function extractStyleProp(styleStr, prop) {
  if (!styleStr) return null;
  const m = styleStr.match(new RegExp(`(?:^|;)\\s*${prop}\\s*:\\s*([^;]+)`, 'i'));
  return m ? m[1].trim() : null;
}

function normalizeCssColor(colorStr) {
  if (!colorStr) return null;
  colorStr = colorStr.trim();
  if (/^#[0-9a-f]{3,8}$/i.test(colorStr)) return colorStr.toLowerCase();
  const rgb = colorStr.match(/^rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)$/i);
  if (rgb) return '#' + [rgb[1], rgb[2], rgb[3]].map(n => parseInt(n, 10).toString(16).padStart(2, '0')).join('');
  const named = { white: '#ffffff', black: '#000000', red: '#ff0000', blue: '#0000ff', green: '#008000', gray: '#808080', grey: '#808080' };
  return named[colorStr.toLowerCase()] || colorStr;
}

function emptyParagraph() {
  return { type: 'paragraph', content: [] };
}


// ═══════════════════════════════════════════════════════════════════════════════
// SECTION 3: tiptapToJsx — TipTap JSON → React Email .jsx source code
// ═══════════════════════════════════════════════════════════════════════════════

function tiptapToJsx(doc, componentName, variables, subject) {
  const nodes = doc.content || [];

  // Collect {{ params.X }} variable names used in this template
  const usedVarNames = collectParamVars(nodes);

  // Build props map: shortName → fallback
  const propsMap = new Map();
  for (const name of usedVarNames) {
    propsMap.set(name, '');
  }
  for (const v of variables || []) {
    const shortName = v.name.replace(/^params\./, '');
    if (propsMap.has(shortName)) propsMap.set(shortName, v.fallback || '');
  }

  // Determine which React Email components are needed
  const usedComponents = collectUsedComponents(nodes);
  const allComponents = ['Html', 'Head', 'Body', 'Container', ...usedComponents];
  const uniqueComponents = [...new Set(allComponents)];

  // Generate JSX for content blocks
  const blocksJsx = nodes
    .map(node => nodeToJsx(node, 3))
    .filter(Boolean)
    .join('\n');

  // Build props parameter
  let propsParam = '';
  if (propsMap.size > 0) {
    const entries = [...propsMap.entries()]
      .map(([k, v]) => `  ${k} = ${JSON.stringify(v)},`)
      .join('\n');
    propsParam = `{\n${entries}\n} = {}`;
  }

  const importLine = `import { ${uniqueComponents.join(', ')} } from '@react-email/components';`;
  const subjectExport = subject ? `\nexport const subject = ${JSON.stringify(subject)};\n` : '';
  const fnSignature = propsParam
    ? `export default function ${componentName}(${propsParam}) {`
    : `export default function ${componentName}() {`;

  return [
    importLine,
    subjectExport,
    fnSignature,
    `  return (`,
    `    <Html>`,
    `      <Head />`,
    `      <Body style={{ backgroundColor: '#ffffff', margin: 0, padding: 0 }}>`,
    `        <Container style={{ maxWidth: '600px', margin: '0 auto' }}>`,
    blocksJsx || `          {/* empty */}`,
    `        </Container>`,
    `      </Body>`,
    `    </Html>`,
    `  );`,
    `}`,
    '',
  ].join('\n');
}

// Collect all {{ params.X }} variable short-names from TipTap content
function collectParamVars(nodes) {
  const vars = new Set();
  const RE = /\{\{\s*params\.(\w+)\s*\}\}/g;

  function scan(node) {
    if (node.type === 'text' && node.text) {
      for (const m of node.text.matchAll(RE)) vars.add(m[1]);
    }
    if (node.attrs) {
      for (const val of Object.values(node.attrs)) {
        if (typeof val === 'string') {
          for (const m of val.matchAll(RE)) vars.add(m[1]);
        }
      }
    }
    if (node.marks) {
      for (const mark of node.marks) {
        if (mark.attrs) {
          for (const val of Object.values(mark.attrs)) {
            if (typeof val === 'string') {
              for (const m of val.matchAll(RE)) vars.add(m[1]);
            }
          }
        }
      }
    }
    if (node.content) for (const child of node.content) scan(child);
  }

  for (const node of nodes) scan(node);
  return [...vars];
}

// Determine which React Email components are needed
function collectUsedComponents(nodes) {
  const comps = new Set();
  function scan(node) {
    switch (node.type) {
      case 'paragraph':
      case 'heading':
      case 'bulletList':
      case 'orderedList':
        comps.add('Text'); break;
      case 'blockImage':
        comps.add('Img');
        if (node.attrs?.href) comps.add('Link');
        break;
      case 'blockButton': comps.add('Button'); break;
      case 'blockDivider': comps.add('Hr'); break;
      case 'blockSpacer': comps.add('Section'); break;
      case 'blockColumns': comps.add('Section'); comps.add('Column'); break;
      case 'blockSocialIcons': comps.add('Row'); comps.add('Link'); comps.add('Img'); break;
    }
    if (node.content) for (const child of node.content) scan(child);
  }
  for (const node of nodes) scan(node);
  return [...comps];
}

// ─── Node → JSX string ────────────────────────────────────────────────────────

function nodeToJsx(node, indentLevel) {
  const pad = '  '.repeat(indentLevel);
  switch (node.type) {
    case 'paragraph':    return paragraphToJsx(node, pad);
    case 'heading':      return headingToJsx(node, pad);
    case 'bulletList':
    case 'orderedList':  return bulletListToJsx(node, pad);
    case 'blockImage':   return imageToJsx(node, pad);
    case 'blockButton':  return buttonToJsx(node, pad);
    case 'blockDivider': return dividerToJsx(node, pad);
    case 'blockSpacer':  return spacerToJsx(node, pad);
    case 'blockColumns': return columnsToJsx(node, pad, indentLevel);
    case 'blockSocialIcons': return socialIconsToJsx(node, pad);
    default:             return null;
  }
}

function paragraphToJsx(node, pad) {
  const align = node.attrs?.textAlign || 'left';
  const htmlExpr = inlineToJsExpr(node.content || []);
  if (!htmlExpr) return null;
  return [
    `${pad}<Text`,
    `${pad}  style={{ textAlign: '${align}', color: '#676a6c', fontSize: '16px', lineHeight: '1.6', margin: '0 0 8px 0' }}`,
    `${pad}  dangerouslySetInnerHTML={{ __html: ${htmlExpr} }}`,
    `${pad}/>`,
  ].join('\n');
}

function headingToJsx(node, pad) {
  const level = node.attrs?.level || 2;
  const sizes   = { 1: '32px', 2: '24px', 3: '20px' };
  const weights = { 1: 700,    2: 700,    3: 600    };
  const htmlExpr = inlineToJsExpr(node.content || []);
  if (!htmlExpr) return null;
  return [
    `${pad}<Text`,
    `${pad}  style={{ fontSize: '${sizes[level] || '24px'}', fontWeight: ${weights[level] || 700}, lineHeight: '1.3', margin: '0 0 12px 0', color: '#333333' }}`,
    `${pad}  dangerouslySetInnerHTML={{ __html: ${htmlExpr} }}`,
    `${pad}/>`,
  ].join('\n');
}

function bulletListToJsx(node, pad) {
  const bullet = node.type === 'orderedList' ? null : '• ';
  const items = (node.content || []).map((item, idx) => {
    const paragraphs = (item.content || []).flatMap(p => {
      const html = buildInlineHtmlStr(p.content || []);
      const prefix = bullet ?? `${idx + 1}. `;
      return html ? [`${prefix}${html}`] : [];
    });
    return paragraphs.join('<br/>');
  }).filter(Boolean);

  if (items.length === 0) return null;
  const htmlExpr = wrapAsJsExpr(items.join('<br/>'));
  return [
    `${pad}<Text`,
    `${pad}  style={{ margin: '0 0 8px 0', paddingLeft: '16px', lineHeight: '1.6', fontSize: '16px', color: '#676a6c' }}`,
    `${pad}  dangerouslySetInnerHTML={{ __html: ${htmlExpr} }}`,
    `${pad}/>`,
  ].join('\n');
}

function imageToJsx(node, pad) {
  const { src = '', alt = '', width = '100%', align = 'center', href } = node.attrs || {};
  const w = typeof width === 'number' ? `${width}px` : width;
  const margin = align === 'center' ? '0 auto' : align === 'right' ? '0 0 0 auto' : '0';

  const imgLines = [
    `${pad}<Img`,
    `${pad}  src=${jsxAttrValue(src)}`,
    `${pad}  alt=${jsxAttrValue(alt)}`,
    `${pad}  width="${w}"`,
    `${pad}  style={{ display: 'block', margin: '${margin}' }}`,
    `${pad}/>`,
  ].join('\n');

  if (href) {
    return [
      `${pad}<Link href=${jsxAttrValue(href)}>`,
      imgLines.split('\n').map(l => '  ' + l).join('\n'),
      `${pad}</Link>`,
    ].join('\n');
  }
  return imgLines;
}

function buttonToJsx(node, pad) {
  const {
    label = 'Click here', href = '#',
    backgroundColor = '#D97706', color = '#ffffff',
    borderRadius = 6,
    paddingTop = 12, paddingBottom = 12, paddingLeft = 24, paddingRight = 24,
    fontSize = 14, fontWeight = 600,
  } = node.attrs || {};

  const labelContent = hasParamVars(label)
    ? substituteToJsxExpr(label)
    : escapeJsxText(label);

  return [
    `${pad}<Button`,
    `${pad}  href=${jsxAttrValue(href)}`,
    `${pad}  style={{`,
    `${pad}    backgroundColor: '${backgroundColor}',`,
    `${pad}    color: '${color}',`,
    `${pad}    borderRadius: '${borderRadius}px',`,
    `${pad}    padding: '${paddingTop}px ${paddingRight}px ${paddingBottom}px ${paddingLeft}px',`,
    `${pad}    fontSize: '${fontSize}px',`,
    `${pad}    fontWeight: ${fontWeight},`,
    `${pad}    textAlign: 'center',`,
    `${pad}    display: 'block',`,
    `${pad}  }}`,
    `${pad}>`,
    `${pad}  ${labelContent}`,
    `${pad}</Button>`,
  ].join('\n');
}

function dividerToJsx(node, pad) {
  const { color = '#E5E7EB', thickness = 1, width = 100 } = node.attrs || {};
  return [
    `${pad}<Hr`,
    `${pad}  style={{ borderColor: '${color}', borderTopWidth: '${thickness}px', width: '${width}%', margin: '16px auto' }}`,
    `${pad}/>`,
  ].join('\n');
}

function spacerToJsx(node, pad) {
  const { height = 24 } = node.attrs || {};
  return `${pad}<Section style={{ padding: '${height}px 0 0 0', margin: 0 }} />`;
}

function columnsToJsx(node, pad, indentLevel) {
  const { ratio = '50-50' } = node.attrs || {};
  const ratioMap = { '50-50': ['50%', '50%'], '33-66': ['33%', '66%'], '66-33': ['66%', '33%'] };
  const [lw, rw] = ratioMap[ratio] || ['50%', '50%'];
  const i1 = '  '.repeat(indentLevel + 1);
  const i2 = '  '.repeat(indentLevel + 2);

  const leftContent = (node.content?.[0]?.content || [])
    .map(n => nodeToJsx(n, indentLevel + 2)).filter(Boolean).join('\n');
  const rightContent = (node.content?.[1]?.content || [])
    .map(n => nodeToJsx(n, indentLevel + 2)).filter(Boolean).join('\n');

  return [
    `${pad}<Section>`,
    `${i1}<Column style={{ width: '${lw}', verticalAlign: 'top' }}>`,
    leftContent || `${i2}{/* empty */}`,
    `${i1}</Column>`,
    `${i1}<Column style={{ width: '${rw}', verticalAlign: 'top' }}>`,
    rightContent || `${i2}{/* empty */}`,
    `${i1}</Column>`,
    `${pad}</Section>`,
  ].join('\n');
}

function socialIconsToJsx(node, pad) {
  const { icons = [] } = node.attrs || {};
  if (icons.length === 0) return null;
  const i1 = pad + '  ';
  const i2 = i1 + '  ';

  const iconLines = icons.map(icon => [
    `${i1}<Link href=${jsxAttrValue(icon.href || '#')} style={{ display: 'inline-block', margin: '0 6px' }}>`,
    `${i2}<Img src=${jsxAttrValue(icon.iconUrl || '')} alt=${jsxAttrValue(icon.network || '')} width="24" height="24" />`,
    `${i1}</Link>`,
  ].join('\n')).join('\n');

  return [
    `${pad}<Row style={{ textAlign: 'center', margin: '8px 0' }}>`,
    iconLines,
    `${pad}</Row>`,
  ].join('\n');
}


// ─── Inline HTML string helpers ───────────────────────────────────────────────

/**
 * Build a JS expression (quoted string or template literal) from TipTap inline nodes.
 * Returns null if there is no meaningful content.
 */
function inlineToJsExpr(nodes) {
  if (!nodes || nodes.length === 0) return null;
  const html = buildInlineHtmlStr(nodes);
  if (!html.trim()) return null;
  return wrapAsJsExpr(html);
}

/** Build an HTML string from TipTap inline nodes, preserving {{ params.X }} tokens. */
function buildInlineHtmlStr(nodes) {
  if (!nodes) return '';
  return nodes.map(inlineNodeToHtmlStr).join('');
}

function inlineNodeToHtmlStr(node) {
  if (node.type === 'hardBreak') return '<br/>';
  if (node.type !== 'text') return '';

  let text = htmlEscapePreservingVars(node.text || '');

  if (node.marks) {
    for (const mark of node.marks) {
      switch (mark.type) {
        case 'bold':      text = `<strong>${text}</strong>`; break;
        case 'italic':    text = `<em>${text}</em>`; break;
        case 'underline': text = `<u>${text}</u>`; break;
        case 'code':      text = `<code>${text}</code>`; break;
        case 'link': {
          const href = mark.attrs?.href || '#';
          // preserve variable tokens in href
          const hrefStr = hasParamVars(href)
            ? href.replace(/\{\{\s*params\.(\w+)\s*\}\}/g, '${$1}')
            : href;
          if (hasParamVars(href)) {
            text = `<a href="\${${href.match(/params\.(\w+)/)?.[1] || 'url'}}">${text}</a>`;
          } else {
            text = `<a href="${href}">${text}</a>`;
          }
          break;
        }
        case 'textStyle':
          if (mark.attrs?.color) text = `<span style="color:${mark.attrs.color}">${text}</span>`;
          break;
      }
    }
  }
  return text;
}

/** HTML-escape a string while preserving {{ params.X }} tokens unchanged. */
function htmlEscapePreservingVars(str) {
  const parts = str.split(/(\{\{\s*params\.\w+\s*\}\})/g);
  return parts.map((part, i) => {
    if (i % 2 === 1) return part; // variable token — keep as-is
    return part.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }).join('');
}

/**
 * Wrap an HTML string as a JS expression for dangerouslySetInnerHTML.
 * If it contains {{ params.X }}, uses a template literal with ${X} substitution.
 * Otherwise returns a double-quoted string.
 */
function wrapAsJsExpr(htmlStr) {
  if (!hasParamVars(htmlStr)) {
    const escaped = htmlStr.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
    return `"${escaped}"`;
  }
  const withSubs = substituteParamVars(htmlStr);
  const escaped = withSubs.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\n/g, '\\n');
  return `\`${escaped}\``;
}

/** JSX attribute value: "static", {varName}, or {`tem${plate}`} */
function jsxAttrValue(str) {
  if (!str) return '""';
  if (!hasParamVars(str)) {
    return `"${str.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
  }
  const pure = str.match(/^\{\{\s*params\.(\w+)\s*\}\}$/);
  if (pure) return `{${pure[1]}}`;
  const withSubs = substituteParamVars(str).replace(/`/g, '\\`');
  return `{\`${withSubs}\`}`;
}

/** Convert a button label string to JSX children content. */
function substituteToJsxExpr(str) {
  const pure = str.match(/^\{\{\s*params\.(\w+)\s*\}\}$/);
  if (pure) return `{${pure[1]}}`;
  const withSubs = substituteParamVars(str).replace(/`/g, '\\`');
  return `{\`${withSubs}\`}`;
}

/** Escape a static string for use as JSX text content. */
function escapeJsxText(str) {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function hasParamVars(str) {
  return /\{\{\s*params\.\w+\s*\}\}/.test(str);
}

function substituteParamVars(str) {
  return str.replace(/\{\{\s*params\.(\w+)\s*\}\}/g, '$$$1}').replace(/\$(\w+)\}/g, '${$1}');
}


// ─── Naming utilities ─────────────────────────────────────────────────────────

function toSlug(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function toPascalCase(slug) {
  return slug.split('-').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join('');
}
